FROM php:8.1-fpm-alpine

WORKDIR /var/www

RUN apk --update add wget \
    curl \
    build-base \
    libmemcached-dev \
    libmcrypt-dev \
    libxml2-dev \
    pcre-dev \
    zlib-dev \
    autoconf \
    cyrus-sasl-dev \
    libgsasl-dev \
    oniguruma-dev \
    openssl \
    openssl-dev




RUN curl -sS https://getcomposer.org/installer | php -- \
    --filename=composer \
    --install-dir=/usr/local/bin

RUN apk add libpng-dev
RUN apk add freetype-dev
RUN apk add libjpeg-turbo-dev
RUN docker-php-ext-install pdo_mysql
#RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
RUN  docker-php-ext-configure gd --with-freetype --with-jpeg
# RUN docker-php-ext-install -j$(nproc) gd iconv mcrypt
RUN docker-php-ext-install gd
RUN rm /var/cache/apk/*


